version: "3.3"
services:  
  database:
    image: package-database:latest
    build:
      context: ./database/
    container_name: package-database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  server:
    image: package-server:latest
    build:
      context: ./server/
    container_name: package-server
    environment:
      MYSQL_HOST: "package-database"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3000:3000"
