replicaCount: 1
image:
  repository: package-ingress
  tag: latest
  pullPolicy: Never
service:
  type: NodePort
  port: 80
  nodePort: 32080
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - minikube
env:
  - name: PACKAGE_SERVER_HOST
    value: "package-server-production.production.svc.cluster.local"
  - name: PACKAGE_SERVER_PORT
    value: "3000"
