replicaCount: 1
image:
  repository: package-server
  tag: latest # this should be the commit SHA of a wishful release
  pullPolicy: Never
service:
  type: ClusterIP
  port: 3000
  healthcheck:
    path: /health
resources: 
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 512Mi
env:
  - name: PORT
    value: "3000"
  - name: MYSQL_HOST
    value: package-database-production.production.svc.cluster.local
  - name: MYSQL_USER
    value: root
  - name: MYSQL_PASSWORD
    value: root
