replicaCount: 1
image:
  repository: package-ingress
  tag: latest
  pullPolicy: Never
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
  path: /
    - delta
