replicaCount: 1
image:
  repository: package-database
  tag: latest
  pullPolicy: Never
service:
  type: ClusterIP
  port: 3306
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
env:
  - name: MYSQL_ROOT_PASSWORD 
    value: root
